yoo
hubreviewapp/hubreview pull request #127
Opened 2024-04-04 07:23 UTC by Ece-Kahraman

2024-04-07 09:33 UTC, aysekelleci commented
deneme

2024-04-07 12:03 UTC, Ece-Kahraman commented
<!--Using HubReview-->
> deneme
> https://github.com/hubreviewapp/hubreview/pull/127#issuecomment-2041386626 

never gonna let you down

2024-04-07 13:13 UTC, aysekelleci commented
<!--Using HubReview-->
> deneme
> https://github.com/hubreviewapp/hubreview/pull/127#issuecomment-2041386626 

heyyo

2024-04-09 11:13 UTC, Ece-Kahraman commented
<!--Using HubReview-->**ACTIVE**: <p>hello</p>

2024-04-18 11:48 UTC, Ece-Kahraman commented
<!--Using HubReview-->
> **ACTIVE**: <p>hello</p>
> https://github.com/hubreviewapp/hubreview/pull/127#issuecomment-2044763642 

sup

2024-04-19 16:06 UTC, aysekelleci commented
> **ACTIVE**:
> hello

hi

2024-04-19 17:03 UTC, aysekelleci commented
<!--Using HubReview-->
> deneme
> https://github.com/hubreviewapp/hubreview/pull/127#issuecomment-2041386626 

sdkfl

2024-04-19 17:25 UTC, aysekelleci commented
<!--Using HubReview-->**ACTIVE**: <p>sdfghn</p>

2024-04-19 17:26 UTC, aysekelleci commented
<!--Using HubReview-->
> **ACTIVE**: <p>sdfghn</p>
> https://github.com/hubreviewapp/hubreview/pull/127#issuecomment-2066993971 

reply

2024-04-23 11:47 UTC, vIremAydin requested changes

2024-04-23 11:47 UTC, vIremAydin commented on README.md
> +BBBBBBBBBBBBB
<!--Using HubReview-->
none(non-blocking): hell no

2024-04-23 12:14 UTC, vIremAydin commented
<!--Using HubReview-->
> deneme
> https://github.com/hubreviewapp/hubreview/pull/127#issuecomment-2041386626 

deneme 11

2024-04-23 12:18 UTC, vIremAydin commented
<!--Using HubReview-->**ACTIVE**: <p><strong>the bold type</strong></p>

2024-04-23 12:25 UTC, vIremAydin requested changes

2024-04-23 12:25 UTC, vIremAydin commented on README.md
>  allam sana geliyorum
<!--Using HubReview-->
question(blocking): lol

2024-04-23 12:26 UTC, vIremAydin commented on README.md
> +BBBBBBBBBBBBB
qszq

2024-04-23 12:58 UTC, aysekelleci commented
<!--Using HubReview-->
> 
> **ACTIVE**: <p><strong>the bold type</strong></p>
> https://github.com/hubreviewapp/hubreview/pull/127#issuecomment-2072151987 

hello
> https://github.com/hubreviewapp/hubreview/pull/127#issuecomment-2072152205 

reply

2024-05-01 15:46 UTC, vIremAydin commented
<!--Using HubReview-->
> 
> **ACTIVE**: <p><strong>the bold type</strong></p>
> https://github.com/hubreviewapp/hubreview/pull/127#issuecomment-2072151987 

hello
> https://github.com/hubreviewapp/hubreview/pull/127#issuecomment-2072152205 

replied

2024-05-01 15:46 UTC, vIremAydin commented
<!--Using HubReview-->
> **ACTIVE**: <p><strong>the bold type</strong></p>
> https://github.com/hubreviewapp/hubreview/pull/127#issuecomment-2072151987 

you are great

2024-05-05 22:05 UTC, aysekelleci commented
<!--Using HubReview-->
> 
> 
> **ACTIVE**: <p><strong>the bold type</strong></p>
> https://github.com/hubreviewapp/hubreview/pull/127#issuecomment-2072151987 

hello
> https://github.com/hubreviewapp/hubreview/pull/127#issuecomment-2072152205 

reply
> https://github.com/hubreviewapp/hubreview/pull/127#issuecomment-2072232468 

sljakdj

2024-05-06 11:35 UTC, closed without merging